source 'https://github.com/CocoaPods/Specs.git'

workspace 'MPDynamicSkeleton'
project 'MPDynamicSkeleton.xcodeproj'

use_frameworks!
platform :ios, '10.0'

target 'MPDynamicSkeleton_Example' do
  pod 'MPDynamicSkeleton', :path => '../'
end
